service: slr-backend 

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  environment:
    MONGO_DB_ENV: ${env:MONGO_DB_ENV}
    MONGO_DB_USER: ${env:MONGO_DB_USER}
    MONGO_DB_PASS: ${env:MONGO_DB_PASS}
    MONGO_DB_URL: ${env:MONGO_DB_URL}
    SPRINGER_API_KEY: ${env:SPRINGER_API_KEY}
    ELSEVIER_API_KEY: ${env:ELSEVIER_API_KEY}
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  dry_query:
    handler: handler.dry_query
    events:
      - http:
          path: query
          method: post
          cors: true
  add_review:
    handler: handler.add_review
    events:
      - http:
          path: review
          method: post
          cors:
            origin: '*'
  get_review_by_id:
    handler: handler.get_review_by_id
    events:
      - http:
          path: review/{id}
          method: get
          request:
            parameters:
              path:
                id: true
          cors:
            origin: '*'
  delete_review:
    handler: handler.delete_review
    events:
      - http:
          path: review/{id}
          method: delete
          request:
            parameters:
              path:
                id: true
          cors:
            origin: '*'
  update_review:
    handler: handler.update_review
    events:
      - http:
          path: review/{id}
          method: put
          request:
            parameters:
              path:
                id: true
          cors:
            origin: '*'